language: ruby
rvm:
  - 2.1.6

# http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/
#
sudo: false

# http://docs.travis-ci.com/user/caching/
#
cache: bundler

addons:
  postgresql: '9.4'

script:
  - TZ=Europe/London DATABASE_USER=postgres RAILS_ENV=test bundle exec rake db:drop db:create db:migrate test --backtrace
