language: ruby
matrix:
  include:
    - rvm: 2.2.7
    - rvm: 2.1.10

# http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/
#
sudo: false

# http://docs.travis-ci.com/user/caching/
#
cache: bundler

addons:
  postgresql: "9.6"

script:
  - TZ=Europe/London DATABASE_USER=postgres RAILS_ENV=test bundle exec rake test
