# TrackRecord PostgreSQL Travis database configuration. For new file
# starting points, see "database_blank.yml" and "database_sqlite.yml".

dbinfo: &dbinfo
  adapter: postgresql
  encoding: utf8
  host: localhost

production:
  <<: *dbinfo
  database: trackrecord

development:
  <<: *dbinfo
  database: trackrecord-devel

# Warning: The database defined as 'test' will be erased and re-generated
# from your development database when you run 'rake'. Do not set this to
# the same as development or production.

test:
  <<: *dbinfo
  database: trackrecord-test
